stages:
  - stage: Deploy
    displayName: 'Deploy to Azure App Service'
    jobs:
      - deployment: DeployToAzure
        environment: 'production'
        strategy:
          runOnce:
            deploy:
              steps:
                # Baixando o artefato publicado pela build
                - task: DownloadBuildArtifacts@0
                  inputs:
                    artifactName: 'drop'  # Nome do artefato publicado
                    downloadPath: '$(System.ArtifactsDirectory)'

                # Realizando o deploy no Azure App Service
                - task: AzureWebApp@1
                  inputs:
                    appName: 'NomeDoAppService'  # Substitua pelo nome do seu App Service
                    package: '$(System.ArtifactsDirectory)/drop/**/*.zip'  # Caminho para o arquivo .zip gerado na build
